#ifndef MONSET_MBEDTLS_CONFIG_H
#define MONSET_MBEDTLS_CONFIG_H

/* Загружаем базовый конфиг */
#include "mbedtls/mbedtls_config.h"

/* ── Отключаем TLS 1.3 полностью ─────────────────────────────── */
#ifdef MBEDTLS_SSL_PROTO_TLS1_3
#undef MBEDTLS_SSL_PROTO_TLS1_3
#endif
#ifdef MBEDTLS_SSL_TLS1_3_COMPATIBILITY_MODE
#undef MBEDTLS_SSL_TLS1_3_COMPATIBILITY_MODE
#endif
#ifdef MBEDTLS_SSL_TLS1_3_KEY_EXCHANGE_MODE_EPHEMERAL_ENABLED
#undef MBEDTLS_SSL_TLS1_3_KEY_EXCHANGE_MODE_EPHEMERAL_ENABLED
#endif
#ifdef MBEDTLS_SSL_TLS1_3_KEY_EXCHANGE_MODE_PSK_ENABLED
#undef MBEDTLS_SSL_TLS1_3_KEY_EXCHANGE_MODE_PSK_ENABLED
#endif
#ifdef MBEDTLS_SSL_TLS1_3_KEY_EXCHANGE_MODE_PSK_EPHEMERAL_ENABLED
#undef MBEDTLS_SSL_TLS1_3_KEY_EXCHANGE_MODE_PSK_EPHEMERAL_ENABLED
#endif
#ifdef MBEDTLS_SSL_EARLY_DATA
#undef MBEDTLS_SSL_EARLY_DATA
#endif
#ifdef MBEDTLS_SSL_RECORD_SIZE_LIMIT
#undef MBEDTLS_SSL_RECORD_SIZE_LIMIT
#endif
#ifdef MBEDTLS_SSL_KEYING_MATERIAL_EXPORT
#undef MBEDTLS_SSL_KEYING_MATERIAL_EXPORT
#endif

/* ── Отключаем PSA crypto и все зависимости ──────────────────── */
#ifdef MBEDTLS_PSA_CRYPTO_C
#undef MBEDTLS_PSA_CRYPTO_C
#endif
#ifdef MBEDTLS_PSA_CRYPTO_CLIENT
#undef MBEDTLS_PSA_CRYPTO_CLIENT
#endif
#ifdef MBEDTLS_PSA_CRYPTO_CONFIG
#undef MBEDTLS_PSA_CRYPTO_CONFIG
#endif
#ifdef MBEDTLS_PSA_CRYPTO_STORAGE_C
#undef MBEDTLS_PSA_CRYPTO_STORAGE_C
#endif
#ifdef MBEDTLS_PSA_ITS_FILE_C
#undef MBEDTLS_PSA_ITS_FILE_C
#endif
#ifdef MBEDTLS_USE_PSA_CRYPTO
#undef MBEDTLS_USE_PSA_CRYPTO
#endif

/* LMS/LMOTS требуют PSA_CRYPTO_C */
#ifdef MBEDTLS_LMS_C
#undef MBEDTLS_LMS_C
#endif
#ifdef MBEDTLS_LMS_PRIVATE
#undef MBEDTLS_LMS_PRIVATE
#endif

/* ── Отключаем DTLS (не нужен для HTTPS) ─────────────────────── */
#ifdef MBEDTLS_SSL_PROTO_DTLS
#undef MBEDTLS_SSL_PROTO_DTLS
#endif
#ifdef MBEDTLS_SSL_DTLS_ANTI_REPLAY
#undef MBEDTLS_SSL_DTLS_ANTI_REPLAY
#endif
#ifdef MBEDTLS_SSL_DTLS_HELLO_VERIFY
#undef MBEDTLS_SSL_DTLS_HELLO_VERIFY
#endif
#ifdef MBEDTLS_SSL_DTLS_CLIENT_PORT_REUSE
#undef MBEDTLS_SSL_DTLS_CLIENT_PORT_REUSE
#endif
#ifdef MBEDTLS_SSL_DTLS_CONNECTION_ID
#undef MBEDTLS_SSL_DTLS_CONNECTION_ID
#endif
#ifdef MBEDTLS_SSL_DTLS_CONNECTION_ID_COMPAT
#undef MBEDTLS_SSL_DTLS_CONNECTION_ID_COMPAT
#endif
#ifdef MBEDTLS_SSL_DTLS_SRTP
#undef MBEDTLS_SSL_DTLS_SRTP
#endif

/* ── Отключаем ECDHE/ECC key exchange ────────────────────────── */
#ifdef MBEDTLS_KEY_EXCHANGE_ECDHE_RSA_ENABLED
#undef MBEDTLS_KEY_EXCHANGE_ECDHE_RSA_ENABLED
#endif
#ifdef MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED
#undef MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED
#endif
#ifdef MBEDTLS_KEY_EXCHANGE_ECDHE_PSK_ENABLED
#undef MBEDTLS_KEY_EXCHANGE_ECDHE_PSK_ENABLED
#endif
#ifdef MBEDTLS_KEY_EXCHANGE_ECJPAKE_ENABLED
#undef MBEDTLS_KEY_EXCHANGE_ECJPAKE_ENABLED
#endif
#ifdef MBEDTLS_KEY_EXCHANGE_ECDH_ECDSA_ENABLED
#undef MBEDTLS_KEY_EXCHANGE_ECDH_ECDSA_ENABLED
#endif
#ifdef MBEDTLS_KEY_EXCHANGE_ECDH_RSA_ENABLED
#undef MBEDTLS_KEY_EXCHANGE_ECDH_RSA_ENABLED
#endif

/* ── Уменьшаем буферы SSL ────────────────────────────────────── */
#ifdef MBEDTLS_SSL_IN_CONTENT_LEN
#undef MBEDTLS_SSL_IN_CONTENT_LEN
#endif
#define MBEDTLS_SSL_IN_CONTENT_LEN  4096

#ifdef MBEDTLS_SSL_OUT_CONTENT_LEN
#undef MBEDTLS_SSL_OUT_CONTENT_LEN
#endif
#define MBEDTLS_SSL_OUT_CONTENT_LEN 4096

/* ── Embedded-специфичные опции ──────────────────────────────── */
#ifndef MBEDTLS_NO_PLATFORM_ENTROPY
#define MBEDTLS_NO_PLATFORM_ENTROPY
#endif
#ifndef MBEDTLS_ENTROPY_HARDWARE_ALT
#define MBEDTLS_ENTROPY_HARDWARE_ALT
#endif

/* platform_util.c требует MS_TIME_ALT на платформах без POSIX/Win */
#ifndef MBEDTLS_PLATFORM_MS_TIME_ALT
#define MBEDTLS_PLATFORM_MS_TIME_ALT
#endif

#ifdef MBEDTLS_NET_C
#undef MBEDTLS_NET_C
#endif
#ifdef MBEDTLS_TIMING_C
#undef MBEDTLS_TIMING_C
#endif
#ifdef MBEDTLS_FS_IO
#undef MBEDTLS_FS_IO
#endif

#endif /* MONSET_MBEDTLS_CONFIG_H */
